from app.models import ClusterDeployment, Deployment, Package, Repository, Workflows

deployments: list[Deployment] = [
    Deployment(
        id="frontend",
        title="Frontend",
        emoji="🖥️",
        package=Package(
            username="interviewandhealth",
            image="frontend",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="Frontend",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/frontend/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="user-service",
        title="User Service",
        emoji="👤",
        package=Package(
            username="interviewandhealth",
            image="user-service",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="User-Service",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/user-service/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="interview-service",
        title="Interview Service",
        emoji="🎤",
        package=Package(
            username="interviewandhealth",
            image="interview-service",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="Interview-Service",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/interview-service/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="conversation-service",
        title="Conversation Service",
        emoji="💬",
        package=Package(
            username="interviewandhealth",
            image="conversation-service",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="Conversation-Service",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/conversation-service/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="payment-service",
        title="Payment Service",
        emoji="💳",
        package=Package(
            username="interviewandhealth",
            image="payment-service",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="Payment-Service",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/payment-service/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="job-service",
        title="Job Service",
        emoji="👷",
        package=Package(
            username="interviewandhealth",
            image="job-service",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="Job-Service",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/job-service/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="scheduler-service",
        title="Scheduler Service",
        emoji="🗓️",
        package=Package(
            username="interviewandhealth",
            image="scheduler-service",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="Scheduler-Service",
        ),
        workflows=Workflows(
            development="build.yml",
            production="deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/scheduler-service/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="rabbitmq-keepalive",
        title="Cron Job - RabbitMQ Keep Alive",
        emoji="⏰🐇",
        package=Package(
            username="interviewandhealth",
            image="cronjob/rabbitmq-keepalive",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="CronJobs",
        ),
        workflows=Workflows(
            development="rabbitmq-keepalive-build.yml",
            production="rabbitmq-keepalive-deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/cronjobs/rabbitmq-keepalive/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
    Deployment(
        id="process-pending-feedbacks",
        title="Cron Job - Process Pending Feedbacks",
        emoji="⏰📝",
        package=Package(
            username="interviewandhealth",
            image="cronjob/process-pending-feedbacks",
        ),
        repository=Repository(
            owner="InterviewAndHealth",
            repo="CronJobs",
        ),
        workflows=Workflows(
            development="process-pending-feedbacks-build.yml",
            production="process-pending-feedbacks-deploy.yml",
        ),
        deployments=ClusterDeployment(
            repository=Repository(
                owner="InterviewAndHealth",
                repo="Cluster",
            ),
            base_path="services/cronjobs/process-pending-feedbacks/overlays",
            development="development/kustomization.yaml",
            production="production/kustomization.yaml",
        ),
    ),
]
